In [1]:
!pip install pydeck pandas ipywidgets requests

Requirement already satisfied: pydeck in C:\Users\cyber\PyCharmMiscProject\.venv\Lib\site-packages (0.9.1)
Requirement already satisfied: pandas in C:\Users\cyber\PyCharmMiscProject\.venv\Lib\site-packages (2.3.3)
Requirement already satisfied: ipywidgets in C:\Users\cyber\PyCharmMiscProject\.venv\Lib\site-packages (8.1.8)
Requirement already satisfied: requests in C:\Users\cyber\PyCharmMiscProject\.venv\Lib\site-packages (2.32.5)
Requirement already satisfied: jinja2>=2.10.1 in C:\Users\cyber\PyCharmMiscProject\.venv\Lib\site-packages (from pydeck) (3.1.6)
Requirement already satisfied: numpy>=1.16.4 in C:\Users\cyber\PyCharmMiscProject\.venv\Lib\site-packages (from pydeck) (2.4.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\cyber\PyCharmMiscProject\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\cyber\PyCharmMiscProject\.venv\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\cyber\PyCharmMiscProject\.venv\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: comm>=0.1.3 in C:\Users\cyber\PyCharmMiscProject\.venv\Lib\site-packages (from ipywidgets) (0.2.3)
Requirement already satisfied: ipython>=6.1.0 in C:\Users\cyber\PyCharmMiscProject\.venv\Lib\site-packages (from ipywidgets) (9.10.0)
Requirement already satisfied: traitlets>=4.3.1 in C:\Users\cyber\PyCharmMiscProject\.venv\Lib\site-packages (from ipywidgets) (5.14.3)
Requirement already satisfied: widgetsnbextension~=4.0.14 in C:\Users\cyber\PyCharmMiscProject\.venv\Lib\site-packages (from ipywidgets) (4.0.15)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in C:\Users\cyber\PyCharmMiscProject\.venv\Lib\site-packages (from ipywidgets) (3.0.16)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\cyber\PyCharmMiscProject\.venv\Lib\site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\cyber\PyCharmMiscProject\.venv\Lib\site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\Users\cyber\PyCharmMiscProject\.venv\Lib\site-packages (from requests) (2.6.2)
Requirement already satisfied: certifi>=2017.4.17 in C:\Users\cyber\PyCharmMiscProject\.venv\Lib\site-packages (from requests) (2025.11.12)
Requirement already satisfied: colorama>=0.4.4 in C:\Users\cyber\PyCharmMiscProject\.venv\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.4.6)
Requirement already satisfied: decorator>=4.3.2 in C:\Users\cyber\PyCharmMiscProject\.venv\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in C:\Users\cyber\PyCharmMiscProject\.venv\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (1.1.1)
Requirement already satisfied: jedi>=0.18.1 in C:\Users\cyber\PyCharmMiscProject\.venv\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.19.2)
Requirement already satisfied: matplotlib-inline>=0.1.5 in C:\Users\cyber\PyCharmMiscProject\.venv\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.2.1)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in C:\Users\cyber\PyCharmMiscProject\.venv\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (3.0.52)
Requirement already satisfied: pygments>=2.11.0 in C:\Users\cyber\PyCharmMiscProject\.venv\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (2.19.2)
Requirement already satisfied: stack_data>=0.6.0 in C:\Users\cyber\PyCharmMiscProject\.venv\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.6.3)
Requirement already satisfied: wcwidth in C:\Users\cyber\PyCharmMiscProject\.venv\Lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.6.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in C:\Users\cyber\PyCharmMiscProject\.venv\Lib\site-packages (from jedi>=0.18.1->ipython>=6.1.0->ipywidgets) (0.8.6)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\cyber\PyCharmMiscProject\.venv\Lib\site-packages (from jinja2>=2.10.1->pydeck) (3.0.3)
Requirement already satisfied: six>=1.5 in C:\Users\cyber\PyCharmMiscProject\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: executing>=1.2.0 in C:\Users\cyber\PyCharmMiscProject\.venv\Lib\site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in C:\Users\cyber\PyCharmMiscProject\.venv\Lib\site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (3.0.1)
Requirement already satisfied: pure-eval in C:\Users\cyber\PyCharmMiscProject\.venv\Lib\site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (0.2.3)

WARNING: Ignoring invalid distribution ~umpy (C:\Users\cyber\PyCharmMiscProject\.venv\Lib\site-packages)
WARNING: Ignoring invalid distribution ~umpy (C:\Users\cyber\PyCharmMiscProject\.venv\Lib\site-packages)
WARNING: Ignoring invalid distribution ~umpy (C:\Users\cyber\PyCharmMiscProject\.venv\Lib\site-packages)

In [2]:
import pydeck as pdk
import pandas as pd
import numpy as np
import ipywidgets as widgets
from IPython.display import display

In [3]:
# Fallback sample (works offline)
df = pd.DataFrame({
    "city": ["Delhi", "Mumbai", "Chennai", "Kolkata", "Bengaluru"],
    "lat": [28.6139, 19.0760, 13.0827, 22.5726, 12.9716],
    "lon": [77.2090, 72.8777, 80.2707, 88.3639, 77.5946],
    "height": [300000, 200000, 250000, 180000, 220000]
})

# If you have a GeoJSON (e.g., buildings), load like:
# import json
# with open("buildings.geojson") as f:
#     gj = json.load(f)
# Then use GeoJsonLayer (see Cell 6)
df

        city      lat      lon  height
0      Delhi  28.6139  77.2090  300000
1     Mumbai  19.0760  72.8777  200000
2    Chennai  13.0827  80.2707  250000
3    Kolkata  22.5726  88.3639  180000
4  Bengaluru  12.9716  77.5946  220000

In [4]:
def height_to_color(h, hmin, hmax):
    t = (h - hmin) / (hmax - hmin + 1e-9)
    # blue → green → red gradient
    r = int(255 * t)
    g = int(255 * (1 - abs(t - 0.5) * 2))
    b = int(255 * (1 - t))
    return [r, g, b]

def add_colors(data):
    hmin, hmax = data["height"].min(), data["height"].max()
    data = data.copy()
    data["color"] = data["height"].apply(lambda h: height_to_color(h, hmin, hmax))
    return data

df_colored = add_colors(df)
df_colored.head()

        city      lat      lon  height            color
0      Delhi  28.6139  77.2090  300000      [254, 0, 0]
1     Mumbai  19.0760  72.8777  200000    [42, 84, 212]
2    Chennai  13.0827  80.2707  250000  [148, 212, 106]
3    Kolkata  22.5726  88.3639  180000      [0, 0, 255]
4  Bengaluru  12.9716  77.5946  220000   [84, 169, 170]

In [5]:
scale_slider = widgets.FloatSlider(
    value=0.1, min=0.02, max=0.5, step=0.01,
    description="Scale", continuous_update=False
)

style_dropdown = widgets.Dropdown(
    options={
        "Dark": "mapbox://styles/mapbox/dark-v10",
        "Light": "mapbox://styles/mapbox/light-v9",
        "Satellite": "mapbox://styles/mapbox/satellite-v9"
    },
    value="mapbox://styles/mapbox/dark-v10",
    description="Style"
)

display(scale_slider, style_dropdown)

FloatSlider(value=0.1, continuous_update=False, description='Scale', max=0.5, min=0.02, step=0.01)

Dropdown(description='Style', options={'Dark': 'mapbox://styles/mapbox/dark-v10', 'Light': 'mapbox://styles/ma…

In [6]:
def make_deck(data, scale, map_style):
    layer = pdk.Layer(
        "ColumnLayer",
        data,
        get_position='[lon, lat]',
        get_elevation="height",
        elevation_scale=scale,
        radius=40000,
        get_fill_color="color",
        pickable=True,
        auto_highlight=True
    )

    view = pdk.ViewState(latitude=22, longitude=78, zoom=4, pitch=45)

    deck = pdk.Deck(
        layers=[layer],
        initial_view_state=view,
        map_style=map_style,
        tooltip={"text": "{city}\nHeight: {height}"}
    )
    return deck

make_deck(df_colored, scale_slider.value, style_dropdown.value)

{
  "initialViewState": {
    "latitude": 22,
    "longitude": 78,
    "pitch": 45,
    "zoom": 4
  },
  "layers": [
    {
      "@@type": "ColumnLayer",
      "autoHighlight": true,
      "data": [
        {
          "city": "Delhi",
          "color": [
            254,
            0,
            0
          ],
          "height": 300000,
          "lat": 28.6139,
          "lon": 77.209
        },
        {
          "city": "Mumbai",
          "color": [
            42,
            84,
            212
          ],
          "height": 200000,
          "lat": 19.076,
          "lon": 72.8777
        },
        {
          "city": "Chennai",
          "color": [
            148,
            212,
            106
          ],
          "height": 250000,
          "lat": 13.0827,
          "lon": 80.2707
        },
        {
          "city": "Kolkata",
          "color": [
            0,
            0,
            255
          ],
          "height": 180000,
          "lat": 22.5726,
          "lon": 88.3639
        },
        {
          "city": "Bengaluru",
          "color": [
            84,
            169,
            170
          ],
          "height": 220000,
          "lat": 12.9716,
          "lon": 77.5946
        }
      ],
      "elevationScale": 0.1,
      "getElevation": "@@=height",
      "getFillColor": "@@=color",
      "getPosition": "@@=[lon, lat]",
      "id": "d2c9b956-4e5e-47d2-8fef-35cdb811997c",
      "pickable": true,
      "radius": 40000
    }
  ],
  "mapProvider": "carto",
  "mapStyle": "mapbox://styles/mapbox/dark-v10",
  "views": [
    {
      "@@type": "MapView",
      "controller": true
    }
  ]
}

In [7]:
def update(scale, style):
    display(make_deck(df_colored, scale, style))

widgets.interact(update, scale=scale_slider, style=style_dropdown);

interactive(children=(FloatSlider(value=0.1, continuous_update=False, description='Scale', max=0.5, min=0.02, …

In [8]:
# Simulate growth over frames
frames = 30

def animate_growth(frame):
    factor = 0.2 + (frame / frames) * 0.8
    data = df.copy()
    data["height"] = (data["height"] * factor).astype(int)
    data = add_colors(data)
    return make_deck(data, scale_slider.value, style_dropdown.value)

# Play through frames (manual loop for notebook stability)
for f in range(frames):
    display(animate_growth(f))

{
  "initialViewState": {
    "latitude": 22,
    "longitude": 78,
    "pitch": 45,
    "zoom": 4
  },
  "layers": [
    {
      "@@type": "ColumnLayer",
      "autoHighlight": true,
      "data": [
        {
          "city": "Delhi",
          "color": [
            254,
            0,
            0
          ],
          "height": 60000,
          "lat": 28.6139,
          "lon": 77.209
        },
        {
          "city": "Mumbai",
          "color": [
            42,
            84,
            212
          ],
          "height": 40000,
          "lat": 19.076,
          "lon": 72.8777
        },
        {
          "city": "Chennai",
          "color": [
            148,
            212,
            106
          ],
          "height": 50000,
          "lat": 13.0827,
          "lon": 80.2707
        },
        {
          "city": "Kolkata",
          "color": [
            0,
            0,
            255
          ],
          "height": 36000,
          "lat": 22.5726,
          "lon": 88.3639
        },
        {
          "city": "Bengaluru",
          "color": [
            84,
            169,
            170
          ],
          "height": 44000,
          "lat": 12.9716,
          "lon": 77.5946
        }
      ],
      "elevationScale": 0.21,
      "getElevation": "@@=height",
      "getFillColor": "@@=color",
      "getPosition": "@@=[lon, lat]",
      "id": "e3df1eb3-da06-49cd-b09f-c92fdc91ce6f",
      "pickable": true,
      "radius": 40000
    }
  ],
  "mapProvider": "carto",
  "mapStyle": "mapbox://styles/mapbox/dark-v10",
  "views": [
    {
      "@@type": "MapView",
      "controller": true
    }
  ]
}

{
  "initialViewState": {
    "latitude": 22,
    "longitude": 78,
    "pitch": 45,
    "zoom": 4
  },
  "layers": [
    {
      "@@type": "ColumnLayer",
      "autoHighlight": true,
      "data": [
        {
          "city": "Delhi",
          "color": [
            254,
            0,
            0
          ],
          "height": 68000,
          "lat": 28.6139,
          "lon": 77.209
        },
        {
          "city": "Mumbai",
          "color": [
            42,
            84,
            212
          ],
          "height": 45333,
          "lat": 19.076,
          "lon": 72.8777
        },
        {
          "city": "Chennai",
          "color": [
            148,
            212,
            106
          ],
          "height": 56666,
          "lat": 13.0827,
          "lon": 80.2707
        },
        {
          "city": "Kolkata",
          "color": [
            0,
            0,
            255
          ],
          "height": 40800,
          "lat": 22.5726,
          "lon": 88.3639
        },
        {
          "city": "Bengaluru",
          "color": [
            84,
            169,
            170
          ],
          "height": 49866,
          "lat": 12.9716,
          "lon": 77.5946
        }
      ],
      "elevationScale": 0.21,
      "getElevation": "@@=height",
      "getFillColor": "@@=color",
      "getPosition": "@@=[lon, lat]",
      "id": "3a2daddc-e102-4f84-803b-10f7b9ff3666",
      "pickable": true,
      "radius": 40000
    }
  ],
  "mapProvider": "carto",
  "mapStyle": "mapbox://styles/mapbox/dark-v10",
  "views": [
    {
      "@@type": "MapView",
      "controller": true
    }
  ]
}

{
  "initialViewState": {
    "latitude": 22,
    "longitude": 78,
    "pitch": 45,
    "zoom": 4
  },
  "layers": [
    {
      "@@type": "ColumnLayer",
      "autoHighlight": true,
      "data": [
        {
          "city": "Delhi",
          "color": [
            254,
            0,
            0
          ],
          "height": 76000,
          "lat": 28.6139,
          "lon": 77.209
        },
        {
          "city": "Mumbai",
          "color": [
            42,
            84,
            212
          ],
          "height": 50666,
          "lat": 19.076,
          "lon": 72.8777
        },
        {
          "city": "Chennai",
          "color": [
            148,
            212,
            106
          ],
          "height": 63333,
          "lat": 13.0827,
          "lon": 80.2707
        },
        {
          "city": "Kolkata",
          "color": [
            0,
            0,
            255
          ],
          "height": 45600,
          "lat": 22.5726,
          "lon": 88.3639
        },
        {
          "city": "Bengaluru",
          "color": [
            84,
            169,
            170
          ],
          "height": 55733,
          "lat": 12.9716,
          "lon": 77.5946
        }
      ],
      "elevationScale": 0.21,
      "getElevation": "@@=height",
      "getFillColor": "@@=color",
      "getPosition": "@@=[lon, lat]",
      "id": "3fbd19f7-4b90-4eac-8f1a-b34fe98d67c7",
      "pickable": true,
      "radius": 40000
    }
  ],
  "mapProvider": "carto",
  "mapStyle": "mapbox://styles/mapbox/dark-v10",
  "views": [
    {
      "@@type": "MapView",
      "controller": true
    }
  ]
}

{
  "initialViewState": {
    "latitude": 22,
    "longitude": 78,
    "pitch": 45,
    "zoom": 4
  },
  "layers": [
    {
      "@@type": "ColumnLayer",
      "autoHighlight": true,
      "data": [
        {
          "city": "Delhi",
          "color": [
            254,
            0,
            0
          ],
          "height": 84000,
          "lat": 28.6139,
          "lon": 77.209
        },
        {
          "city": "Mumbai",
          "color": [
            42,
            84,
            212
          ],
          "height": 56000,
          "lat": 19.076,
          "lon": 72.8777
        },
        {
          "city": "Chennai",
          "color": [
            148,
            212,
            106
          ],
          "height": 70000,
          "lat": 13.0827,
          "lon": 80.2707
        },
        {
          "city": "Kolkata",
          "color": [
            0,
            0,
            255
          ],
          "height": 50400,
          "lat": 22.5726,
          "lon": 88.3639
        },
        {
          "city": "Bengaluru",
          "color": [
            84,
            169,
            170
          ],
          "height": 61600,
          "lat": 12.9716,
          "lon": 77.5946
        }
      ],
      "elevationScale": 0.21,
      "getElevation": "@@=height",
      "getFillColor": "@@=color",
      "getPosition": "@@=[lon, lat]",
      "id": "1a950e2d-a3c0-4335-bb73-64684e892203",
      "pickable": true,
      "radius": 40000
    }
  ],
  "mapProvider": "carto",
  "mapStyle": "mapbox://styles/mapbox/dark-v10",
  "views": [
    {
      "@@type": "MapView",
      "controller": true
    }
  ]
}

{
  "initialViewState": {
    "latitude": 22,
    "longitude": 78,
    "pitch": 45,
    "zoom": 4
  },
  "layers": [
    {
      "@@type": "ColumnLayer",
      "autoHighlight": true,
      "data": [
        {
          "city": "Delhi",
          "color": [
            254,
            0,
            0
          ],
          "height": 92000,
          "lat": 28.6139,
          "lon": 77.209
        },
        {
          "city": "Mumbai",
          "color": [
            42,
            84,
            212
          ],
          "height": 61333,
          "lat": 19.076,
          "lon": 72.8777
        },
        {
          "city": "Chennai",
          "color": [
            148,
            212,
            106
          ],
          "height": 76666,
          "lat": 13.0827,
          "lon": 80.2707
        },
        {
          "city": "Kolkata",
          "color": [
            0,
            0,
            255
          ],
          "height": 55200,
          "lat": 22.5726,
          "lon": 88.3639
        },
        {
          "city": "Bengaluru",
          "color": [
            84,
            169,
            170
          ],
          "height": 67466,
          "lat": 12.9716,
          "lon": 77.5946
        }
      ],
      "elevationScale": 0.21,
      "getElevation": "@@=height",
      "getFillColor": "@@=color",
      "getPosition": "@@=[lon, lat]",
      "id": "56b20c48-0314-4aac-908a-cd2beb83986d",
      "pickable": true,
      "radius": 40000
    }
  ],
  "mapProvider": "carto",
  "mapStyle": "mapbox://styles/mapbox/dark-v10",
  "views": [
    {
      "@@type": "MapView",
      "controller": true
    }
  ]
}

{
  "initialViewState": {
    "latitude": 22,
    "longitude": 78,
    "pitch": 45,
    "zoom": 4
  },
  "layers": [
    {
      "@@type": "ColumnLayer",
      "autoHighlight": true,
      "data": [
        {
          "city": "Delhi",
          "color": [
            254,
            0,
            0
          ],
          "height": 100000,
          "lat": 28.6139,
          "lon": 77.209
        },
        {
          "city": "Mumbai",
          "color": [
            42,
            84,
            212
          ],
          "height": 66666,
          "lat": 19.076,
          "lon": 72.8777
        },
        {
          "city": "Chennai",
          "color": [
            148,
            212,
            106
          ],
          "height": 83333,
          "lat": 13.0827,
          "lon": 80.2707
        },
        {
          "city": "Kolkata",
          "color": [
            0,
            0,
            255
          ],
          "height": 60000,
          "lat": 22.5726,
          "lon": 88.3639
        },
        {
          "city": "Bengaluru",
          "color": [
            84,
            169,
            170
          ],
          "height": 73333,
          "lat": 12.9716,
          "lon": 77.5946
        }
      ],
      "elevationScale": 0.21,
      "getElevation": "@@=height",
      "getFillColor": "@@=color",
      "getPosition": "@@=[lon, lat]",
      "id": "96ad1d75-04f4-410a-8c91-e19c6c32a366",
      "pickable": true,
      "radius": 40000
    }
  ],
  "mapProvider": "carto",
  "mapStyle": "mapbox://styles/mapbox/dark-v10",
  "views": [
    {
      "@@type": "MapView",
      "controller": true
    }
  ]
}

{
  "initialViewState": {
    "latitude": 22,
    "longitude": 78,
    "pitch": 45,
    "zoom": 4
  },
  "layers": [
    {
      "@@type": "ColumnLayer",
      "autoHighlight": true,
      "data": [
        {
          "city": "Delhi",
          "color": [
            254,
            0,
            0
          ],
          "height": 108000,
          "lat": 28.6139,
          "lon": 77.209
        },
        {
          "city": "Mumbai",
          "color": [
            42,
            84,
            212
          ],
          "height": 72000,
          "lat": 19.076,
          "lon": 72.8777
        },
        {
          "city": "Chennai",
          "color": [
            148,
            212,
            106
          ],
          "height": 90000,
          "lat": 13.0827,
          "lon": 80.2707
        },
        {
          "city": "Kolkata",
          "color": [
            0,
            0,
            255
          ],
          "height": 64800,
          "lat": 22.5726,
          "lon": 88.3639
        },
        {
          "city": "Bengaluru",
          "color": [
            84,
            169,
            170
          ],
          "height": 79200,
          "lat": 12.9716,
          "lon": 77.5946
        }
      ],
      "elevationScale": 0.21,
      "getElevation": "@@=height",
      "getFillColor": "@@=color",
      "getPosition": "@@=[lon, lat]",
      "id": "b9402f2b-e755-439f-8387-e4c081f3e0bd",
      "pickable": true,
      "radius": 40000
    }
  ],
  "mapProvider": "carto",
  "mapStyle": "mapbox://styles/mapbox/dark-v10",
  "views": [
    {
      "@@type": "MapView",
      "controller": true
    }
  ]
}

{
  "initialViewState": {
    "latitude": 22,
    "longitude": 78,
    "pitch": 45,
    "zoom": 4
  },
  "layers": [
    {
      "@@type": "ColumnLayer",
      "autoHighlight": true,
      "data": [
        {
          "city": "Delhi",
          "color": [
            254,
            0,
            0
          ],
          "height": 116000,
          "lat": 28.6139,
          "lon": 77.209
        },
        {
          "city": "Mumbai",
          "color": [
            42,
            84,
            212
          ],
          "height": 77333,
          "lat": 19.076,
          "lon": 72.8777
        },
        {
          "city": "Chennai",
          "color": [
            148,
            212,
            106
          ],
          "height": 96666,
          "lat": 13.0827,
          "lon": 80.2707
        },
        {
          "city": "Kolkata",
          "color": [
            0,
            0,
            255
          ],
          "height": 69600,
          "lat": 22.5726,
          "lon": 88.3639
        },
        {
          "city": "Bengaluru",
          "color": [
            84,
            169,
            170
          ],
          "height": 85066,
          "lat": 12.9716,
          "lon": 77.5946
        }
      ],
      "elevationScale": 0.21,
      "getElevation": "@@=height",
      "getFillColor": "@@=color",
      "getPosition": "@@=[lon, lat]",
      "id": "da4ff6f3-8fef-43e7-81ae-9e3094b4a834",
      "pickable": true,
      "radius": 40000
    }
  ],
  "mapProvider": "carto",
  "mapStyle": "mapbox://styles/mapbox/dark-v10",
  "views": [
    {
      "@@type": "MapView",
      "controller": true
    }
  ]
}

{
  "initialViewState": {
    "latitude": 22,
    "longitude": 78,
    "pitch": 45,
    "zoom": 4
  },
  "layers": [
    {
      "@@type": "ColumnLayer",
      "autoHighlight": true,
      "data": [
        {
          "city": "Delhi",
          "color": [
            254,
            0,
            0
          ],
          "height": 124000,
          "lat": 28.6139,
          "lon": 77.209
        },
        {
          "city": "Mumbai",
          "color": [
            42,
            84,
            212
          ],
          "height": 82666,
          "lat": 19.076,
          "lon": 72.8777
        },
        {
          "city": "Chennai",
          "color": [
            148,
            212,
            106
          ],
          "height": 103333,
          "lat": 13.0827,
          "lon": 80.2707
        },
        {
          "city": "Kolkata",
          "color": [
            0,
            0,
            255
          ],
          "height": 74400,
          "lat": 22.5726,
          "lon": 88.3639
        },
        {
          "city": "Bengaluru",
          "color": [
            84,
            169,
            170
          ],
          "height": 90933,
          "lat": 12.9716,
          "lon": 77.5946
        }
      ],
      "elevationScale": 0.21,
      "getElevation": "@@=height",
      "getFillColor": "@@=color",
      "getPosition": "@@=[lon, lat]",
      "id": "28a71202-6686-4894-958c-af90c19bfe32",
      "pickable": true,
      "radius": 40000
    }
  ],
  "mapProvider": "carto",
  "mapStyle": "mapbox://styles/mapbox/dark-v10",
  "views": [
    {
      "@@type": "MapView",
      "controller": true
    }
  ]
}

{
  "initialViewState": {
    "latitude": 22,
    "longitude": 78,
    "pitch": 45,
    "zoom": 4
  },
  "layers": [
    {
      "@@type": "ColumnLayer",
      "autoHighlight": true,
      "data": [
        {
          "city": "Delhi",
          "color": [
            254,
            0,
            0
          ],
          "height": 132000,
          "lat": 28.6139,
          "lon": 77.209
        },
        {
          "city": "Mumbai",
          "color": [
            42,
            84,
            212
          ],
          "height": 88000,
          "lat": 19.076,
          "lon": 72.8777
        },
        {
          "city": "Chennai",
          "color": [
            148,
            212,
            106
          ],
          "height": 110000,
          "lat": 13.0827,
          "lon": 80.2707
        },
        {
          "city": "Kolkata",
          "color": [
            0,
            0,
            255
          ],
          "height": 79200,
          "lat": 22.5726,
          "lon": 88.3639
        },
        {
          "city": "Bengaluru",
          "color": [
            84,
            169,
            170
          ],
          "height": 96800,
          "lat": 12.9716,
          "lon": 77.5946
        }
      ],
      "elevationScale": 0.21,
      "getElevation": "@@=height",
      "getFillColor": "@@=color",
      "getPosition": "@@=[lon, lat]",
      "id": "9e0ee11e-c2b1-42c2-bd90-95f229e39991",
      "pickable": true,
      "radius": 40000
    }
  ],
  "mapProvider": "carto",
  "mapStyle": "mapbox://styles/mapbox/dark-v10",
  "views": [
    {
      "@@type": "MapView",
      "controller": true
    }
  ]
}

{
  "initialViewState": {
    "latitude": 22,
    "longitude": 78,
    "pitch": 45,
    "zoom": 4
  },
  "layers": [
    {
      "@@type": "ColumnLayer",
      "autoHighlight": true,
      "data": [
        {
          "city": "Delhi",
          "color": [
            254,
            0,
            0
          ],
          "height": 140000,
          "lat": 28.6139,
          "lon": 77.209
        },
        {
          "city": "Mumbai",
          "color": [
            42,
            84,
            212
          ],
          "height": 93333,
          "lat": 19.076,
          "lon": 72.8777
        },
        {
          "city": "Chennai",
          "color": [
            148,
            212,
            106
          ],
          "height": 116666,
          "lat": 13.0827,
          "lon": 80.2707
        },
        {
          "city": "Kolkata",
          "color": [
            0,
            0,
            255
          ],
          "height": 84000,
          "lat": 22.5726,
          "lon": 88.3639
        },
        {
          "city": "Bengaluru",
          "color": [
            84,
            169,
            170
          ],
          "height": 102666,
          "lat": 12.9716,
          "lon": 77.5946
        }
      ],
      "elevationScale": 0.21,
      "getElevation": "@@=height",
      "getFillColor": "@@=color",
      "getPosition": "@@=[lon, lat]",
      "id": "f80f37ef-d7a7-4b95-9fce-1937bec10ea9",
      "pickable": true,
      "radius": 40000
    }
  ],
  "mapProvider": "carto",
  "mapStyle": "mapbox://styles/mapbox/dark-v10",
  "views": [
    {
      "@@type": "MapView",
      "controller": true
    }
  ]
}

{
  "initialViewState": {
    "latitude": 22,
    "longitude": 78,
    "pitch": 45,
    "zoom": 4
  },
  "layers": [
    {
      "@@type": "ColumnLayer",
      "autoHighlight": true,
      "data": [
        {
          "city": "Delhi",
          "color": [
            254,
            0,
            0
          ],
          "height": 148000,
          "lat": 28.6139,
          "lon": 77.209
        },
        {
          "city": "Mumbai",
          "color": [
            42,
            84,
            212
          ],
          "height": 98666,
          "lat": 19.076,
          "lon": 72.8777
        },
        {
          "city": "Chennai",
          "color": [
            148,
            212,
            106
          ],
          "height": 123333,
          "lat": 13.0827,
          "lon": 80.2707
        },
        {
          "city": "Kolkata",
          "color": [
            0,
            0,
            255
          ],
          "height": 88800,
          "lat": 22.5726,
          "lon": 88.3639
        },
        {
          "city": "Bengaluru",
          "color": [
            84,
            169,
            170
          ],
          "height": 108533,
          "lat": 12.9716,
          "lon": 77.5946
        }
      ],
      "elevationScale": 0.21,
      "getElevation": "@@=height",
      "getFillColor": "@@=color",
      "getPosition": "@@=[lon, lat]",
      "id": "008a2752-8283-4e9c-ae30-cc0fa83dbf69",
      "pickable": true,
      "radius": 40000
    }
  ],
  "mapProvider": "carto",
  "mapStyle": "mapbox://styles/mapbox/dark-v10",
  "views": [
    {
      "@@type": "MapView",
      "controller": true
    }
  ]
}

{
  "initialViewState": {
    "latitude": 22,
    "longitude": 78,
    "pitch": 45,
    "zoom": 4
  },
  "layers": [
    {
      "@@type": "ColumnLayer",
      "autoHighlight": true,
      "data": [
        {
          "city": "Delhi",
          "color": [
            254,
            0,
            0
          ],
          "height": 156000,
          "lat": 28.6139,
          "lon": 77.209
        },
        {
          "city": "Mumbai",
          "color": [
            42,
            84,
            212
          ],
          "height": 104000,
          "lat": 19.076,
          "lon": 72.8777
        },
        {
          "city": "Chennai",
          "color": [
            148,
            212,
            106
          ],
          "height": 130000,
          "lat": 13.0827,
          "lon": 80.2707
        },
        {
          "city": "Kolkata",
          "color": [
            0,
            0,
            255
          ],
          "height": 93600,
          "lat": 22.5726,
          "lon": 88.3639
        },
        {
          "city": "Bengaluru",
          "color": [
            84,
            169,
            170
          ],
          "height": 114400,
          "lat": 12.9716,
          "lon": 77.5946
        }
      ],
      "elevationScale": 0.21,
      "getElevation": "@@=height",
      "getFillColor": "@@=color",
      "getPosition": "@@=[lon, lat]",
      "id": "991e36ec-04ec-4804-9695-61cc50070f4d",
      "pickable": true,
      "radius": 40000
    }
  ],
  "mapProvider": "carto",
  "mapStyle": "mapbox://styles/mapbox/dark-v10",
  "views": [
    {
      "@@type": "MapView",
      "controller": true
    }
  ]
}

{
  "initialViewState": {
    "latitude": 22,
    "longitude": 78,
    "pitch": 45,
    "zoom": 4
  },
  "layers": [
    {
      "@@type": "ColumnLayer",
      "autoHighlight": true,
      "data": [
        {
          "city": "Delhi",
          "color": [
            254,
            0,
            0
          ],
          "height": 164000,
          "lat": 28.6139,
          "lon": 77.209
        },
        {
          "city": "Mumbai",
          "color": [
            42,
            84,
            212
          ],
          "height": 109333,
          "lat": 19.076,
          "lon": 72.8777
        },
        {
          "city": "Chennai",
          "color": [
            148,
            212,
            106
          ],
          "height": 136666,
          "lat": 13.0827,
          "lon": 80.2707
        },
        {
          "city": "Kolkata",
          "color": [
            0,
            0,
            255
          ],
          "height": 98400,
          "lat": 22.5726,
          "lon": 88.3639
        },
        {
          "city": "Bengaluru",
          "color": [
            84,
            169,
            170
          ],
          "height": 120266,
          "lat": 12.9716,
          "lon": 77.5946
        }
      ],
      "elevationScale": 0.21,
      "getElevation": "@@=height",
      "getFillColor": "@@=color",
      "getPosition": "@@=[lon, lat]",
      "id": "66121183-39ef-4540-bb39-65fee35322b9",
      "pickable": true,
      "radius": 40000
    }
  ],
  "mapProvider": "carto",
  "mapStyle": "mapbox://styles/mapbox/dark-v10",
  "views": [
    {
      "@@type": "MapView",
      "controller": true
    }
  ]
}

{
  "initialViewState": {
    "latitude": 22,
    "longitude": 78,
    "pitch": 45,
    "zoom": 4
  },
  "layers": [
    {
      "@@type": "ColumnLayer",
      "autoHighlight": true,
      "data": [
        {
          "city": "Delhi",
          "color": [
            254,
            0,
            0
          ],
          "height": 172000,
          "lat": 28.6139,
          "lon": 77.209
        },
        {
          "city": "Mumbai",
          "color": [
            42,
            84,
            212
          ],
          "height": 114666,
          "lat": 19.076,
          "lon": 72.8777
        },
        {
          "city": "Chennai",
          "color": [
            148,
            212,
            106
          ],
          "height": 143333,
          "lat": 13.0827,
          "lon": 80.2707
        },
        {
          "city": "Kolkata",
          "color": [
            0,
            0,
            255
          ],
          "height": 103200,
          "lat": 22.5726,
          "lon": 88.3639
        },
        {
          "city": "Bengaluru",
          "color": [
            84,
            169,
            170
          ],
          "height": 126133,
          "lat": 12.9716,
          "lon": 77.5946
        }
      ],
      "elevationScale": 0.21,
      "getElevation": "@@=height",
      "getFillColor": "@@=color",
      "getPosition": "@@=[lon, lat]",
      "id": "e21f60d1-de68-4561-ace6-46f9c6769f68",
      "pickable": true,
      "radius": 40000
    }
  ],
  "mapProvider": "carto",
  "mapStyle": "mapbox://styles/mapbox/dark-v10",
  "views": [
    {
      "@@type": "MapView",
      "controller": true
    }
  ]
}

{
  "initialViewState": {
    "latitude": 22,
    "longitude": 78,
    "pitch": 45,
    "zoom": 4
  },
  "layers": [
    {
      "@@type": "ColumnLayer",
      "autoHighlight": true,
      "data": [
        {
          "city": "Delhi",
          "color": [
            254,
            0,
            0
          ],
          "height": 180000,
          "lat": 28.6139,
          "lon": 77.209
        },
        {
          "city": "Mumbai",
          "color": [
            42,
            84,
            212
          ],
          "height": 120000,
          "lat": 19.076,
          "lon": 72.8777
        },
        {
          "city": "Chennai",
          "color": [
            148,
            212,
            106
          ],
          "height": 150000,
          "lat": 13.0827,
          "lon": 80.2707
        },
        {
          "city": "Kolkata",
          "color": [
            0,
            0,
            255
          ],
          "height": 108000,
          "lat": 22.5726,
          "lon": 88.3639
        },
        {
          "city": "Bengaluru",
          "color": [
            84,
            169,
            170
          ],
          "height": 132000,
          "lat": 12.9716,
          "lon": 77.5946
        }
      ],
      "elevationScale": 0.21,
      "getElevation": "@@=height",
      "getFillColor": "@@=color",
      "getPosition": "@@=[lon, lat]",
      "id": "6ba28f58-6396-4d05-85a4-e298bb91e3a3",
      "pickable": true,
      "radius": 40000
    }
  ],
  "mapProvider": "carto",
  "mapStyle": "mapbox://styles/mapbox/dark-v10",
  "views": [
    {
      "@@type": "MapView",
      "controller": true
    }
  ]
}

{
  "initialViewState": {
    "latitude": 22,
    "longitude": 78,
    "pitch": 45,
    "zoom": 4
  },
  "layers": [
    {
      "@@type": "ColumnLayer",
      "autoHighlight": true,
      "data": [
        {
          "city": "Delhi",
          "color": [
            254,
            0,
            0
          ],
          "height": 188000,
          "lat": 28.6139,
          "lon": 77.209
        },
        {
          "city": "Mumbai",
          "color": [
            42,
            84,
            212
          ],
          "height": 125333,
          "lat": 19.076,
          "lon": 72.8777
        },
        {
          "city": "Chennai",
          "color": [
            148,
            212,
            106
          ],
          "height": 156666,
          "lat": 13.0827,
          "lon": 80.2707
        },
        {
          "city": "Kolkata",
          "color": [
            0,
            0,
            255
          ],
          "height": 112800,
          "lat": 22.5726,
          "lon": 88.3639
        },
        {
          "city": "Bengaluru",
          "color": [
            84,
            169,
            170
          ],
          "height": 137866,
          "lat": 12.9716,
          "lon": 77.5946
        }
      ],
      "elevationScale": 0.21,
      "getElevation": "@@=height",
      "getFillColor": "@@=color",
      "getPosition": "@@=[lon, lat]",
      "id": "f64b2447-6370-4d2e-9584-88f958079a50",
      "pickable": true,
      "radius": 40000
    }
  ],
  "mapProvider": "carto",
  "mapStyle": "mapbox://styles/mapbox/dark-v10",
  "views": [
    {
      "@@type": "MapView",
      "controller": true
    }
  ]
}

{
  "initialViewState": {
    "latitude": 22,
    "longitude": 78,
    "pitch": 45,
    "zoom": 4
  },
  "layers": [
    {
      "@@type": "ColumnLayer",
      "autoHighlight": true,
      "data": [
        {
          "city": "Delhi",
          "color": [
            254,
            0,
            0
          ],
          "height": 196000,
          "lat": 28.6139,
          "lon": 77.209
        },
        {
          "city": "Mumbai",
          "color": [
            42,
            84,
            212
          ],
          "height": 130666,
          "lat": 19.076,
          "lon": 72.8777
        },
        {
          "city": "Chennai",
          "color": [
            148,
            212,
            106
          ],
          "height": 163333,
          "lat": 13.0827,
          "lon": 80.2707
        },
        {
          "city": "Kolkata",
          "color": [
            0,
            0,
            255
          ],
          "height": 117600,
          "lat": 22.5726,
          "lon": 88.3639
        },
        {
          "city": "Bengaluru",
          "color": [
            84,
            169,
            170
          ],
          "height": 143733,
          "lat": 12.9716,
          "lon": 77.5946
        }
      ],
      "elevationScale": 0.21,
      "getElevation": "@@=height",
      "getFillColor": "@@=color",
      "getPosition": "@@=[lon, lat]",
      "id": "c12bdf2e-b86e-43b1-becb-39621d63c5ff",
      "pickable": true,
      "radius": 40000
    }
  ],
  "mapProvider": "carto",
  "mapStyle": "mapbox://styles/mapbox/dark-v10",
  "views": [
    {
      "@@type": "MapView",
      "controller": true
    }
  ]
}

{
  "initialViewState": {
    "latitude": 22,
    "longitude": 78,
    "pitch": 45,
    "zoom": 4
  },
  "layers": [
    {
      "@@type": "ColumnLayer",
      "autoHighlight": true,
      "data": [
        {
          "city": "Delhi",
          "color": [
            254,
            0,
            0
          ],
          "height": 203999,
          "lat": 28.6139,
          "lon": 77.209
        },
        {
          "city": "Mumbai",
          "color": [
            42,
            85,
            212
          ],
          "height": 136000,
          "lat": 19.076,
          "lon": 72.8777
        },
        {
          "city": "Chennai",
          "color": [
            148,
            212,
            106
          ],
          "height": 169999,
          "lat": 13.0827,
          "lon": 80.2707
        },
        {
          "city": "Kolkata",
          "color": [
            0,
            0,
            255
          ],
          "height": 122399,
          "lat": 22.5726,
          "lon": 88.3639
        },
        {
          "city": "Bengaluru",
          "color": [
            85,
            170,
            169
          ],
          "height": 149600,
          "lat": 12.9716,
          "lon": 77.5946
        }
      ],
      "elevationScale": 0.21,
      "getElevation": "@@=height",
      "getFillColor": "@@=color",
      "getPosition": "@@=[lon, lat]",
      "id": "86f0c87c-6565-4b54-a98f-08358da12381",
      "pickable": true,
      "radius": 40000
    }
  ],
  "mapProvider": "carto",
  "mapStyle": "mapbox://styles/mapbox/dark-v10",
  "views": [
    {
      "@@type": "MapView",
      "controller": true
    }
  ]
}

{
  "initialViewState": {
    "latitude": 22,
    "longitude": 78,
    "pitch": 45,
    "zoom": 4
  },
  "layers": [
    {
      "@@type": "ColumnLayer",
      "autoHighlight": true,
      "data": [
        {
          "city": "Delhi",
          "color": [
            254,
            0,
            0
          ],
          "height": 212000,
          "lat": 28.6139,
          "lon": 77.209
        },
        {
          "city": "Mumbai",
          "color": [
            42,
            84,
            212
          ],
          "height": 141333,
          "lat": 19.076,
          "lon": 72.8777
        },
        {
          "city": "Chennai",
          "color": [
            148,
            212,
            106
          ],
          "height": 176666,
          "lat": 13.0827,
          "lon": 80.2707
        },
        {
          "city": "Kolkata",
          "color": [
            0,
            0,
            255
          ],
          "height": 127200,
          "lat": 22.5726,
          "lon": 88.3639
        },
        {
          "city": "Bengaluru",
          "color": [
            84,
            169,
            170
          ],
          "height": 155466,
          "lat": 12.9716,
          "lon": 77.5946
        }
      ],
      "elevationScale": 0.21,
      "getElevation": "@@=height",
      "getFillColor": "@@=color",
      "getPosition": "@@=[lon, lat]",
      "id": "b309b4d2-46ee-4f80-a6e1-49daf4fad957",
      "pickable": true,
      "radius": 40000
    }
  ],
  "mapProvider": "carto",
  "mapStyle": "mapbox://styles/mapbox/dark-v10",
  "views": [
    {
      "@@type": "MapView",
      "controller": true
    }
  ]
}

{
  "initialViewState": {
    "latitude": 22,
    "longitude": 78,
    "pitch": 45,
    "zoom": 4
  },
  "layers": [
    {
      "@@type": "ColumnLayer",
      "autoHighlight": true,
      "data": [
        {
          "city": "Delhi",
          "color": [
            254,
            0,
            0
          ],
          "height": 220000,
          "lat": 28.6139,
          "lon": 77.209
        },
        {
          "city": "Mumbai",
          "color": [
            42,
            84,
            212
          ],
          "height": 146666,
          "lat": 19.076,
          "lon": 72.8777
        },
        {
          "city": "Chennai",
          "color": [
            148,
            212,
            106
          ],
          "height": 183333,
          "lat": 13.0827,
          "lon": 80.2707
        },
        {
          "city": "Kolkata",
          "color": [
            0,
            0,
            255
          ],
          "height": 132000,
          "lat": 22.5726,
          "lon": 88.3639
        },
        {
          "city": "Bengaluru",
          "color": [
            84,
            169,
            170
          ],
          "height": 161333,
          "lat": 12.9716,
          "lon": 77.5946
        }
      ],
      "elevationScale": 0.21,
      "getElevation": "@@=height",
      "getFillColor": "@@=color",
      "getPosition": "@@=[lon, lat]",
      "id": "c71fa09b-4d55-40e4-a473-e776feff1aa4",
      "pickable": true,
      "radius": 40000
    }
  ],
  "mapProvider": "carto",
  "mapStyle": "mapbox://styles/mapbox/dark-v10",
  "views": [
    {
      "@@type": "MapView",
      "controller": true
    }
  ]
}

{
  "initialViewState": {
    "latitude": 22,
    "longitude": 78,
    "pitch": 45,
    "zoom": 4
  },
  "layers": [
    {
      "@@type": "ColumnLayer",
      "autoHighlight": true,
      "data": [
        {
          "city": "Delhi",
          "color": [
            254,
            0,
            0
          ],
          "height": 228000,
          "lat": 28.6139,
          "lon": 77.209
        },
        {
          "city": "Mumbai",
          "color": [
            42,
            84,
            212
          ],
          "height": 152000,
          "lat": 19.076,
          "lon": 72.8777
        },
        {
          "city": "Chennai",
          "color": [
            148,
            212,
            106
          ],
          "height": 190000,
          "lat": 13.0827,
          "lon": 80.2707
        },
        {
          "city": "Kolkata",
          "color": [
            0,
            0,
            255
          ],
          "height": 136800,
          "lat": 22.5726,
          "lon": 88.3639
        },
        {
          "city": "Bengaluru",
          "color": [
            84,
            169,
            170
          ],
          "height": 167200,
          "lat": 12.9716,
          "lon": 77.5946
        }
      ],
      "elevationScale": 0.21,
      "getElevation": "@@=height",
      "getFillColor": "@@=color",
      "getPosition": "@@=[lon, lat]",
      "id": "31239d4c-95a0-4bd6-903b-220c9922bb38",
      "pickable": true,
      "radius": 40000
    }
  ],
  "mapProvider": "carto",
  "mapStyle": "mapbox://styles/mapbox/dark-v10",
  "views": [
    {
      "@@type": "MapView",
      "controller": true
    }
  ]
}

{
  "initialViewState": {
    "latitude": 22,
    "longitude": 78,
    "pitch": 45,
    "zoom": 4
  },
  "layers": [
    {
      "@@type": "ColumnLayer",
      "autoHighlight": true,
      "data": [
        {
          "city": "Delhi",
          "color": [
            254,
            0,
            0
          ],
          "height": 236000,
          "lat": 28.6139,
          "lon": 77.209
        },
        {
          "city": "Mumbai",
          "color": [
            42,
            84,
            212
          ],
          "height": 157333,
          "lat": 19.076,
          "lon": 72.8777
        },
        {
          "city": "Chennai",
          "color": [
            148,
            212,
            106
          ],
          "height": 196666,
          "lat": 13.0827,
          "lon": 80.2707
        },
        {
          "city": "Kolkata",
          "color": [
            0,
            0,
            255
          ],
          "height": 141600,
          "lat": 22.5726,
          "lon": 88.3639
        },
        {
          "city": "Bengaluru",
          "color": [
            84,
            169,
            170
          ],
          "height": 173066,
          "lat": 12.9716,
          "lon": 77.5946
        }
      ],
      "elevationScale": 0.21,
      "getElevation": "@@=height",
      "getFillColor": "@@=color",
      "getPosition": "@@=[lon, lat]",
      "id": "3f8c9e7e-3fcc-4f80-8234-8646c765b33d",
      "pickable": true,
      "radius": 40000
    }
  ],
  "mapProvider": "carto",
  "mapStyle": "mapbox://styles/mapbox/dark-v10",
  "views": [
    {
      "@@type": "MapView",
      "controller": true
    }
  ]
}

{
  "initialViewState": {
    "latitude": 22,
    "longitude": 78,
    "pitch": 45,
    "zoom": 4
  },
  "layers": [
    {
      "@@type": "ColumnLayer",
      "autoHighlight": true,
      "data": [
        {
          "city": "Delhi",
          "color": [
            254,
            0,
            0
          ],
          "height": 244000,
          "lat": 28.6139,
          "lon": 77.209
        },
        {
          "city": "Mumbai",
          "color": [
            42,
            84,
            212
          ],
          "height": 162666,
          "lat": 19.076,
          "lon": 72.8777
        },
        {
          "city": "Chennai",
          "color": [
            148,
            212,
            106
          ],
          "height": 203333,
          "lat": 13.0827,
          "lon": 80.2707
        },
        {
          "city": "Kolkata",
          "color": [
            0,
            0,
            255
          ],
          "height": 146400,
          "lat": 22.5726,
          "lon": 88.3639
        },
        {
          "city": "Bengaluru",
          "color": [
            84,
            169,
            170
          ],
          "height": 178933,
          "lat": 12.9716,
          "lon": 77.5946
        }
      ],
      "elevationScale": 0.21,
      "getElevation": "@@=height",
      "getFillColor": "@@=color",
      "getPosition": "@@=[lon, lat]",
      "id": "ef1013e8-5782-4a56-af0c-8c60b193beb5",
      "pickable": true,
      "radius": 40000
    }
  ],
  "mapProvider": "carto",
  "mapStyle": "mapbox://styles/mapbox/dark-v10",
  "views": [
    {
      "@@type": "MapView",
      "controller": true
    }
  ]
}

{
  "initialViewState": {
    "latitude": 22,
    "longitude": 78,
    "pitch": 45,
    "zoom": 4
  },
  "layers": [
    {
      "@@type": "ColumnLayer",
      "autoHighlight": true,
      "data": [
        {
          "city": "Delhi",
          "color": [
            254,
            0,
            0
          ],
          "height": 252000,
          "lat": 28.6139,
          "lon": 77.209
        },
        {
          "city": "Mumbai",
          "color": [
            42,
            84,
            212
          ],
          "height": 168000,
          "lat": 19.076,
          "lon": 72.8777
        },
        {
          "city": "Chennai",
          "color": [
            148,
            212,
            106
          ],
          "height": 210000,
          "lat": 13.0827,
          "lon": 80.2707
        },
        {
          "city": "Kolkata",
          "color": [
            0,
            0,
            255
          ],
          "height": 151200,
          "lat": 22.5726,
          "lon": 88.3639
        },
        {
          "city": "Bengaluru",
          "color": [
            84,
            169,
            170
          ],
          "height": 184800,
          "lat": 12.9716,
          "lon": 77.5946
        }
      ],
      "elevationScale": 0.21,
      "getElevation": "@@=height",
      "getFillColor": "@@=color",
      "getPosition": "@@=[lon, lat]",
      "id": "fd7be80a-5f72-4738-bd8a-49a504b701e8",
      "pickable": true,
      "radius": 40000
    }
  ],
  "mapProvider": "carto",
  "mapStyle": "mapbox://styles/mapbox/dark-v10",
  "views": [
    {
      "@@type": "MapView",
      "controller": true
    }
  ]
}

{
  "initialViewState": {
    "latitude": 22,
    "longitude": 78,
    "pitch": 45,
    "zoom": 4
  },
  "layers": [
    {
      "@@type": "ColumnLayer",
      "autoHighlight": true,
      "data": [
        {
          "city": "Delhi",
          "color": [
            254,
            0,
            0
          ],
          "height": 260000,
          "lat": 28.6139,
          "lon": 77.209
        },
        {
          "city": "Mumbai",
          "color": [
            42,
            84,
            212
          ],
          "height": 173333,
          "lat": 19.076,
          "lon": 72.8777
        },
        {
          "city": "Chennai",
          "color": [
            148,
            212,
            106
          ],
          "height": 216666,
          "lat": 13.0827,
          "lon": 80.2707
        },
        {
          "city": "Kolkata",
          "color": [
            0,
            0,
            255
          ],
          "height": 156000,
          "lat": 22.5726,
          "lon": 88.3639
        },
        {
          "city": "Bengaluru",
          "color": [
            84,
            169,
            170
          ],
          "height": 190666,
          "lat": 12.9716,
          "lon": 77.5946
        }
      ],
      "elevationScale": 0.21,
      "getElevation": "@@=height",
      "getFillColor": "@@=color",
      "getPosition": "@@=[lon, lat]",
      "id": "e82458f9-95c7-4296-9394-57b7d865b01b",
      "pickable": true,
      "radius": 40000
    }
  ],
  "mapProvider": "carto",
  "mapStyle": "mapbox://styles/mapbox/dark-v10",
  "views": [
    {
      "@@type": "MapView",
      "controller": true
    }
  ]
}

{
  "initialViewState": {
    "latitude": 22,
    "longitude": 78,
    "pitch": 45,
    "zoom": 4
  },
  "layers": [
    {
      "@@type": "ColumnLayer",
      "autoHighlight": true,
      "data": [
        {
          "city": "Delhi",
          "color": [
            254,
            0,
            0
          ],
          "height": 268000,
          "lat": 28.6139,
          "lon": 77.209
        },
        {
          "city": "Mumbai",
          "color": [
            42,
            84,
            212
          ],
          "height": 178666,
          "lat": 19.076,
          "lon": 72.8777
        },
        {
          "city": "Chennai",
          "color": [
            148,
            212,
            106
          ],
          "height": 223333,
          "lat": 13.0827,
          "lon": 80.2707
        },
        {
          "city": "Kolkata",
          "color": [
            0,
            0,
            255
          ],
          "height": 160800,
          "lat": 22.5726,
          "lon": 88.3639
        },
        {
          "city": "Bengaluru",
          "color": [
            84,
            169,
            170
          ],
          "height": 196533,
          "lat": 12.9716,
          "lon": 77.5946
        }
      ],
      "elevationScale": 0.21,
      "getElevation": "@@=height",
      "getFillColor": "@@=color",
      "getPosition": "@@=[lon, lat]",
      "id": "2f3acc14-ae48-4317-875a-f60bd317dc44",
      "pickable": true,
      "radius": 40000
    }
  ],
  "mapProvider": "carto",
  "mapStyle": "mapbox://styles/mapbox/dark-v10",
  "views": [
    {
      "@@type": "MapView",
      "controller": true
    }
  ]
}

{
  "initialViewState": {
    "latitude": 22,
    "longitude": 78,
    "pitch": 45,
    "zoom": 4
  },
  "layers": [
    {
      "@@type": "ColumnLayer",
      "autoHighlight": true,
      "data": [
        {
          "city": "Delhi",
          "color": [
            254,
            0,
            0
          ],
          "height": 276000,
          "lat": 28.6139,
          "lon": 77.209
        },
        {
          "city": "Mumbai",
          "color": [
            42,
            84,
            212
          ],
          "height": 184000,
          "lat": 19.076,
          "lon": 72.8777
        },
        {
          "city": "Chennai",
          "color": [
            148,
            212,
            106
          ],
          "height": 230000,
          "lat": 13.0827,
          "lon": 80.2707
        },
        {
          "city": "Kolkata",
          "color": [
            0,
            0,
            255
          ],
          "height": 165600,
          "lat": 22.5726,
          "lon": 88.3639
        },
        {
          "city": "Bengaluru",
          "color": [
            84,
            169,
            170
          ],
          "height": 202400,
          "lat": 12.9716,
          "lon": 77.5946
        }
      ],
      "elevationScale": 0.21,
      "getElevation": "@@=height",
      "getFillColor": "@@=color",
      "getPosition": "@@=[lon, lat]",
      "id": "2fdf8b2e-be14-45e3-979e-0470aa84b661",
      "pickable": true,
      "radius": 40000
    }
  ],
  "mapProvider": "carto",
  "mapStyle": "mapbox://styles/mapbox/dark-v10",
  "views": [
    {
      "@@type": "MapView",
      "controller": true
    }
  ]
}

{
  "initialViewState": {
    "latitude": 22,
    "longitude": 78,
    "pitch": 45,
    "zoom": 4
  },
  "layers": [
    {
      "@@type": "ColumnLayer",
      "autoHighlight": true,
      "data": [
        {
          "city": "Delhi",
          "color": [
            254,
            0,
            0
          ],
          "height": 284000,
          "lat": 28.6139,
          "lon": 77.209
        },
        {
          "city": "Mumbai",
          "color": [
            42,
            84,
            212
          ],
          "height": 189333,
          "lat": 19.076,
          "lon": 72.8777
        },
        {
          "city": "Chennai",
          "color": [
            148,
            212,
            106
          ],
          "height": 236666,
          "lat": 13.0827,
          "lon": 80.2707
        },
        {
          "city": "Kolkata",
          "color": [
            0,
            0,
            255
          ],
          "height": 170400,
          "lat": 22.5726,
          "lon": 88.3639
        },
        {
          "city": "Bengaluru",
          "color": [
            84,
            169,
            170
          ],
          "height": 208266,
          "lat": 12.9716,
          "lon": 77.5946
        }
      ],
      "elevationScale": 0.21,
      "getElevation": "@@=height",
      "getFillColor": "@@=color",
      "getPosition": "@@=[lon, lat]",
      "id": "6404aeaf-695c-4271-8547-ace2e8ab5750",
      "pickable": true,
      "radius": 40000
    }
  ],
  "mapProvider": "carto",
  "mapStyle": "mapbox://styles/mapbox/dark-v10",
  "views": [
    {
      "@@type": "MapView",
      "controller": true
    }
  ]
}

{
  "initialViewState": {
    "latitude": 22,
    "longitude": 78,
    "pitch": 45,
    "zoom": 4
  },
  "layers": [
    {
      "@@type": "ColumnLayer",
      "autoHighlight": true,
      "data": [
        {
          "city": "Delhi",
          "color": [
            254,
            0,
            0
          ],
          "height": 292000,
          "lat": 28.6139,
          "lon": 77.209
        },
        {
          "city": "Mumbai",
          "color": [
            42,
            84,
            212
          ],
          "height": 194666,
          "lat": 19.076,
          "lon": 72.8777
        },
        {
          "city": "Chennai",
          "color": [
            148,
            212,
            106
          ],
          "height": 243333,
          "lat": 13.0827,
          "lon": 80.2707
        },
        {
          "city": "Kolkata",
          "color": [
            0,
            0,
            255
          ],
          "height": 175200,
          "lat": 22.5726,
          "lon": 88.3639
        },
        {
          "city": "Bengaluru",
          "color": [
            84,
            169,
            170
          ],
          "height": 214133,
          "lat": 12.9716,
          "lon": 77.5946
        }
      ],
      "elevationScale": 0.21,
      "getElevation": "@@=height",
      "getFillColor": "@@=color",
      "getPosition": "@@=[lon, lat]",
      "id": "cb0fb239-a4a7-4956-88e4-f57f9338325c",
      "pickable": true,
      "radius": 40000
    }
  ],
  "mapProvider": "carto",
  "mapStyle": "mapbox://styles/mapbox/dark-v10",
  "views": [
    {
      "@@type": "MapView",
      "controller": true
    }
  ]
}

In [9]:
# If you have a buildings GeoJSON (with 'height' property):
# import json
# with open("buildings.geojson") as f:
#     gj = json.load(f)

# gj_layer = pdk.Layer(
#     "GeoJsonLayer",
#     gj,
#     extruded=True,
#     get_elevation="properties.height",
#     get_fill_color=[200, 100, 240],
#     pickable=True
# )

# pdk.Deck(
#     layers=[gj_layer],
#     initial_view_state=pdk.ViewState(latitude=22, longitude=78, zoom=12, pitch=45),
#     map_style=style_dropdown.value
# )